# Generated by Django 4.0.6 on 2022-07-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_article_options_alter_article_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='public',
        ),
    ]
