# Generated by Django 4.0.5 on 2022-06-28 17:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='slug',
            field=models.CharField(max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
